### ISSUE TITLE
Packets from some remotes (e.g., RGB) are never sniffed

### ISSUE THREAD

**Issue by xbmcnut** [sidoh/esp8266_milight_hub#266]
Great work so thank you for this. I intend using it to replace a dead v4 Milight bridge and with Hass.io

I have flashed 1.6.5 onto a NodeMCU V2 and have a NRF24L01 module (that was working with My Sensors previously) and I have managed to pair one MiLight bulb (CCT) and can control on/off, brightness and color temp. Based on this, I'm assuming the NRF module is fully working?

My question is I have two different 2.4Ghz RF remotes; one for a flash pendant wave light and another for some RGB LED strips. Both lights work with their consecutive remotes.

When I activate sniffing though and use either remote, I see nothing. I do see data when I use the UI to control the one paired bulb but nothing when using the remotes. Am I supposed to see something when the remote turns on my lights that are not paired with any bridge? 

P.S I have not configured anything in the MQTT section yet other than my broker address.

**Comment by sidoh** [comment]
Any traffic espMH intercepts while in listening mode should show up.  Shouldn't matter if the remotes are paired with anything.

If it's not showing up, it might be a remote model that's not supported.  Could you:

* Let me know what model the remote is?  [futlight.com](http://futlight.com/) seems to have the best product catalog.
* See if there's anything interesting in Serial logs with the `DEBUG_PRINTF` flag enabled?

**Comment by xbmcnut** [comment]
Thanks for the prompt reply. The LED RGB strip remote appears to be a FUT098. The other one is not shown at futlight.com but here is picture.

![img_20180428_223906](https://user-images.githubusercontent.com/1492137/39395798-2ffe69e2-4b37-11e8-82a9-07e524d7b317.jpg)

I'm assuming I'll have to compile to enable the debug flag?

**Comment by xbmcnut** [comment]
I there. Bit rusty on Platformio but tried it with settings below.

![image](https://user-images.githubusercontent.com/1492137/39413659-e2e23cdc-4c81-11e8-810c-6dc880c59ac9.png)

Serial monitor inside Platformio have me nothing but 'null null null null' so I connected to COM4 with Putty. Got valid data when I used an actual FUT007 (found the one that came with my bridge), but the remote pictured above and the FUT098 show nothing. Maybe there are just outside the band of the NRF2401 I have?? I have a LT8900 (with NRF2401+ chip) so maybe I'll try that next.

**Comment by xbmcnut** [comment]
The other module I have is not a LT8900 (as sold to me) but the ultra mini version of the NRF2401+. I hooked it up anyway and get the same results from PuTTy.

```
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result:
*WM: 3
*WM: IP Address:
*WM: 10.0.1.182
Setup complete
Radio is available


                  Packet received: E05A58D540B09778EE030303Packet transformed: 075A1AAB020DE91E77C0  C0C0Failed CRC: expected 0, got 49344
```
Only see these results when pushing buttons on the 'real FUT007. Nothing from the other remotes. Does that tell us anything?

**Comment by sidoh** [comment]
Sniffing on the real LT8900 might even be broken.  So maybe a good thing it wasn't a real one? :)

Definitely looks like an unsupported protocol.  Might even suggest it's knockoff hardware that wasn't implemented to spec.

Could you get a few more packet captures and label them with what button they correspond to?

**Comment by xbmcnut** [comment]
Thanks but that's the thing. The knock off remotes do not generate any code on PuTTy even though the work on their respective lights.

**Comment by sidoh** [comment]
Sorry, I should've been more clear.  I meant the logs from serial output.  Like the stuff you pasted above:

```
Packet received: E05A58D540B09778EE030303Packet transformed: 075A1AAB020DE91E77C0  C0C0Failed CRC: expected 0, got 49344
```

This contains the packet data.

**Comment by sidoh** [comment]
If you're seeing that "Packet received" line, you successfully compiled with DEBUG_PRINTF.

If you're not seeing serial output for your remotes, then they're probably sending on different channels and with different syncwords.  We'd likely need to sniff the SPI bus to get those parameters.

I ordered a FUT007 from ebay, but won't be here for a few weeks.

**Comment by xbmcnut** [comment]
Thanks for all your help, much appreciated. Is there a way I can set up a sniff from the SPI bus?

**Comment by sidoh** [comment]
Doing this is quite a bit more heavyweight than most things required for this project.  You'd need a logic analyzer or oscilloscope, and you'd probably need to take apart the remote so you could attach probes to the appropriate pins.

**Comment by xbmcnut** [comment]
I have an oscilloscope and an electronics background and don' like being beaten by a machine! :) If I can help get these remotes working, I'm happy to help if you can point me in the right direction.

**Comment by sidoh** [comment]
It's not something I actually have any experience with.  I think people basically find the microcontroller or the radio, figure out where the SPI pins are, and watch for messages as actions are taken.  Fancier scopes can decode SPI messages.  Some of the folks who have helped out with this before have digital logic analyzers that do this.

**Comment by xbmcnut** [comment]
Thanks, I appreciate you going to that effort. One of my three remotes is indeed that one that is branded 'Mi-Light' and I can confirm mine works too. The other two do not however. The colour LED strip one is this one https://www.ebay.com/itm/2-4G-LED-RGB-RGBW-Controller-Touch-Screen-RF-Remote-Control-for-RGBW-LED-Strip-/262983073383?roken=cUgayN&soutkn=huGRwh. Can I send you one of those to try? PM me if that is OK.

**Comment by sidoh** [comment]
No need, I think.  I have the milight wifi bridge which is capable of emulating that remote.

I can confirm I'm not seeing any sniffed traffic on my end.

We'll need to get the radio configs (channels, syncwords) to add support for the remote.  [This writeup](https://hackaday.io/project/8758/logs) shows a teardown of a milight device.  My wifi gateway has both of these chips, but I don't have the equipment to do this myself.

Also possible that someone else has done this already.

**Comment by sidoh** [comment]
https://www.amazon.com/gp/product/B077LSG5P2

And to think I was halfheartedly considering getting a $400 Saleae.

**Comment by xbmcnut** [comment]
Wow, that is awesome! If it did the trick, that is all I need too. Thanks.

**Comment by sidoh** [comment]
Just an update here --

This is definitely an issue with the nRF radio code.  I poked around a little bit, but haven't made much progress yet.  (I did, however, manage to get the radio configs for [all remotes supported by the ibox](https://docs.google.com/spreadsheets/d/1eMNn5HmMzNc0LgRBQlcnDYeE7KKCKBPMd15dMbIpqfM/edit#gid=0))

@khmann I recall that some of the radio optimizations you contributed a few months back may have broken sniffing from official devices (this was something we agreed was fine at the time).  Does this sound familiar to you?

If so, any pointers on adding this support back without breaking the radio?  Definitely happy to investigate myself, but thought I'd ask in case you have any ideas offhand.

**Comment by xbmcnut** [comment]
Thanks for the update.

**Comment by xbmcnut** [comment]
Any NRF changes in the esp8266_milight_hub_nodemcuv2-1.8.0-dev1 build?

**Comment by sidoh** [comment]
@xbmcnut hey, sorry I'm so slow getting back to you.  Busy summer!

No, no nRF changes in v1.8.  At the rate I'm going it probably won't make it in.

**Comment by xbmcnut** [comment]
Thanks for the update, appreciated. Let us know once you have something I can test.

**Comment by khmann** [comment]
Sorry, I dropped off the internet for awhile.  The "bug" relates to the not-clearly-defined PL1167 trailer bits; It is possible that these bits are encoded differently by different transmitters and my original patch (RF mod was to replace the rather silly PL1167 software decoding by using nRF hardware filters) had a problem with some of the codeword calculation.  I believe this was actually fixed in the second patch, but that there was some other problem that broke everything.  I've been meaning to pick this back up (and actually use it this time - previously I was just using the reusing your radio code for my own project)

**Comment by khmann** [comment]
Or I'm confused and that's the preamble (I know I verified the preamble function is correct.)  Maybe we need to add the following code (or it's inverse...?)  I'm sorry I'm still trying to figure out platformio to play with it here

[code]
 -  _nrf_pipe[ --nrf_address_pos ] = reverse_bits( ( (_syncword3 >> 12) & 0x0f ) + 0x50 );	// kh: spi doc says trailer is always "5" ?
 +  if (_syncword3 & 0x8000) {
 +    _nrf_pipe[ --nrf_address_pos ] = reverse_bits( ( (_syncword3 >> 12) & 0x0f ) + 0xa0 ); 
 +  } else {
 +    _nrf_pipe[ --nrf_address_pos ] = reverse_bits( ( (_syncword3 >> 12) & 0x0f ) + 0x50 );
 +  }
[/code]

I agree the code needs something, but I think it's worth considering the possibility that some things which _look_ milight compatible, quite simply, aren't.  I've certainly been bitten by that...

**Comment by xbmcnut** [comment]
Thanks guys. Let me know if you'd like me to test a couple of different variants with the 'non-working' remotes I have.

**Comment by xbmcnut** [comment]
Hi there. Any chance this has been improved in 1.8.5?

**Comment by hhaensel** [comment]
Hi there,
I have just tried to sniff commands from my newly acquired FUT098. But no response at all :-(
However, I succeeded in pairing my RGBW controller (FUT027) by chosing an arbitrary device ID, selecting the RGB (!) protocol and pressing `pair` 3s after switching on the controller. I can now control the device via mode/color/brightness/speed.
But also the commands sent from the ESP are not sniffed! So I guess the problem is still  not solved in "1.8.7"?

**Comment by xbmcnut** [comment]
Any progress on this issue Chris?

**Comment by sidoh** [comment]
Hey, sorry for not responding to your earlier comment, @xbmcnut. Slipped through the cracks.  No, I've honestly not looked at it.  No plans to soon, although if it's important to a number of folks I could prioritize it.

**Comment by cristianlivella** [comment]
Same problem here with FUT098 remote and FUT025 controller. I can pair and send comand with NRF24L01, but I can't sniff the remote commands.

**Comment by sidoh** [comment]
FUT098 is supported.

**Comment by cristianlivella** [comment]
> FUT098 is supported.

It isn't working... during sniffing I see only the packets sent by the NRF24L01.

**Comment by sidoh** [comment]
Ah, sorry, missed the context in the thread.

Sniffing doesn't work with it.  Some weird stuff in radio config I haven't had the interest or time to dig into.

Think it's probably somewhere in this change:

https://github.com/sidoh/esp8266_milight_hub/commit/22f3baf667745f6de8887f0482b10073ef0da7e1#diff-955946430a21b8fcd99b02c8913272db

**Comment by xbmcnut** [comment]
I'm a patient man. Let us know if you ever get this fixed and I'll give it another try.

**Comment by xbmcnut** [comment]
Any of the new builds have a fix for this yet Chris?

**Comment by sidoh** [comment]
No, unfortunately not.  If I'm honest, this is not a very fun sort of issue to work on, so sort of hard to drum up the motivation to dig in.

There's probably room in the 1.10 release, but it's possible I won't have the time or motivation to dig through fiddly radio code (apologies for the inconvenience).

**Comment by xbmcnut** [comment]
Thanks. I'll move on.

**Comment by sidoh** [comment]
I'd like to keep the issue open.  It is definitely an actual bug.

**Comment by xbmcnut** [comment]
Understood.

**Comment by sidoh** [comment]
Good news... think I figured this out. :)

Should have a patch up later today.

@khmann called it.  I think the PL1167 trailer is different for the RGB remote (the bits are inverted).

**Comment by xbmcnut** [comment]
Wow, that's great news. Looking forward to testing.

**Comment by sidoh** [comment]
Notes from poking around with the (A) the radio code, and (B) SPI dumps from the wifi gateway:

* The register that defines packet syncword lengths, etc. (`0x20`) is not set, which means the defaults are used:
  * Preamble: 1 byte
  * Syncword: 8 bytes (only 0-2 and 4-6 are set.  others assume the default of 0)
  * Trailer: 4 bits
* There does not seem to be a way to set the values for the preamble or trailer.  I think this means there's something internal to the PL1167 that generates these values.
* Because the values are different based on the syncword, they seem to be a function of the syncword.  (why?  who knows...)
* Seems to depend on the parity of syncword0.
* SPI dump when sending an RGB packet: [rgb_spi.csv.gz](https://github.com/sidoh/esp8266_milight_hub/files/3343910/rgb_spi.csv.gz)
* SPI dump when sending an RGB+CCT packet: [rgb_cct_spi.csv.gz](https://github.com/sidoh/esp8266_milight_hub/files/3343914/rgb_cct_spi.csv.gz)
* SPI dumps ended up not helping much, but attaching them to show that defaults are not changed.
* [PL1167 User Manual](https://github.com/sidoh/esp8266_milight_hub/files/3343915/PL1167_UM_EN_V0.2.pdf)

What ended up revealing what was going on was reducing the nRF24 address with to 4 (from 5), which showed the packet even if the trailer didn't match.  Then you could see what the value of the trailer was for all remote types.  Will hardcode these values into the radio configs.

**Comment by sidoh** [comment]
Fixed in [1.10.0-dev.4](https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.10.0-dev.4).

**Comment by xbmcnut** [comment]
Hi Chris,

Just tried 1.10.0-dev.4 (nodemcuv2) and sadly it is still not sniffing packets from this remote https://github.com/sidoh/esp8266_milight_hub/issues/266#issuecomment-385165682

**Comment by sidoh** [comment]
Hm.

I'm testing with the official wifi gateway, and I am able to sniff RGB packets (where I was not able to before).

Is it able to sniff packets from other remotes?

**Comment by xbmcnut** [comment]
Yes. My original MiLight remote is being sniffed.

**Comment by xbmcnut** [comment]
Sorry, tested [this one](http://futlight.com/productdetails.aspx?id=175&typeid=143) again and sadly, still no go.

**Comment by sidoh** [comment]
Double-checked that I'm not going crazy.  The emulated remote is definitely working, and was not working before.  Think yours might be a separate issue.

Any way you can get a SPI bus dump?

**Comment by sidoh** [comment]
Any chance this is your remote is one of FUT020, FUT021, FUT022?  These don't work for a different reason (their radio configs aren't present at all).

**Comment by xbmcnut** [comment]
My two remotes that don't work aren't any of the above. I'll try connecting another radio and I'll buy a USB debugger for future diagnostics. Anything I can tweak in the web UI?

**Comment by sidoh** [comment]
No settings that should affect whether the remote is picked up or not (especially if it's picking up traffic from other remotes).

Nevertheless, could you post the output of `/settings` and `/about` (censoring any passwords)?

Compiling with `DEBUG_PRINTF` and checking whether there's any output while pressing the remote button would be helpful as well.

i found this remote on ebay for $5, but won't be here for a while.

**Comment by xbmcnut** [comment]
I'm trying to compile the latest zip in PlatformIO with DEBUG_PRINTF uncommented but getting errors.

`Compiling .pioenvs\d1_mini_pro\lib1d5\RichHttpServer_ID6342\RichResponse.cpp.o
.piolibdeps\WebSockets_ID549\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::connectedCb()':
.piolibdeps\WebSockets_ID549\src\WebSocketsClient.cpp:749:22: error: 'class axTLS::WiFiClientSecure' has no member named 'setInsecure'
_client.ssl->setInsecure();
^
*** [.pioenvs\d1_mini_pro\libecd\WebSockets_ID549\WebSocketsClient.cpp.o] Error 1
 [ERROR] Took 30.63 seconds
 
 [SUMMARY]
Environment nodemcuv2   [ERROR]
Environment d1_mini     [ERROR]
Environment esp12       [ERROR]
Environment esp07       [ERROR]
Environment huzzah      [ERROR]
Environment d1_mini_pro [ERROR]
 [ERROR] Took 255.75 seconds`

**Comment by sidoh** [comment]
Are you using a .zip from one of the v1.10 releases?  It includes a fix for this issue (setting the `USING_AXTLS` flag).

Upstream library fixed the issue (see https://github.com/Links2004/arduinoWebSockets/issues/447), but not sure if it's been released yet.

**Comment by sidoh** [comment]
(btw, you can build for a particular platform with, e.g., `pio run -e d1_mini`)

**Comment by xbmcnut** [comment]
Apologies, my bad. Downloaded zip from main page. Downloading dev4 now.

**Comment by xbmcnut** [comment]
Thanks, seems to be working now with Dev4. Managed to create a .bin for d1_mini. Building nodemcuv2 now.

**Comment by sidoh** [comment]
Awesome.  Thanks for pitching in with debugging, much appreciated.

If nothing shows up in serial logs, I'll try uploading an experimental version that doesn't include the trailer in the nRF24 address.

**Comment by xbmcnut** [comment]
Happy to test a custom version. Should be able to test Dev4 with serial in next 2hrs.

**Comment by sidoh** [comment]
Let me know if anything shows up in serial logs (while you're pressing the remote) first so we can narrow down the problem space.

**Comment by xbmcnut** [comment]
Tried serial monitor with Dev4. Working with default MiLight remote [FUT007](http://futlight.com/productdetails.aspx?id=169&typeid=143) but no output at all when using [FUT098](http://futlight.com/productdetails.aspx?id=175&typeid=143) or the remote shown below. Tested another NRF24 module also with the same result.

![image](https://user-images.githubusercontent.com/1492137/60476625-639ee880-9cd0-11e9-885a-f8b0de729ccc.png)

**Comment by xbmcnut** [comment]
Here is one of the problem remotes on Ali https://s.click.aliexpress.com/e/bdmn23bS

**Comment by sidoh** [comment]
Alright, that's strange.

Question -- did this remote work with earlier versions (e.g., 1.5)?

Can you try the attached firmware image?  I've patched it to treat the trailer as a part of the packet rather than the syncword.  The attached image also adds radio (but not remote) support for FUT020 et. al., which have different configs.

[firmware.bin.gz](https://github.com/sidoh/esp8266_milight_hub/files/3351907/firmware.bin.gz)

**Comment by xbmcnut** [comment]
Hi Chris. What hardware is that .bin for? I'm using Nodemcuv2.

**Comment by sidoh** [comment]
It will work with nodemcuv2. It's d1_mini, but they both have 4MB flash, which is all that matters.

**Comment by xbmcnut** [comment]
Sorry Chris, still nothing even on serial. MiLight remote still works, other two nothing under version 1.10.0-dev.4-1-g0dba9a8.

**Comment by sidoh** [comment]
Beginning to feel like you might have some not-Milight gear.

Some questions/asks:

1. Could you post pictures of all of the not-working remotes you have (including the PCB if possible)?
2. Does the really old v1.5 release works for you?
3. Does espMH work to control the LED strip at all? (guessing you're not able to do this because you don't have the remote ID)

Beyond this, think we might be stuck until I get the FUT098 I ordered or you get the logic analyzer and post SPI dumps.

**Comment by xbmcnut** [comment]
Below is the board photo from the FUT098 (clone) that came with a LED strip controller.
https://photos.app.goo.gl/afe4jLW2mn3Q1HDT8
And here is the board of the controller pictured above that came with my dining room lights
https://photos.app.goo.gl/HRrzxccCK6hBHn1Y7

I tried 1.5 built binary as I could not build with PIO and got nothing in the sniffing console when using the two rogue remotes.

When the USB debugger turns up I can provide more info but I'd need guidance on how to do that based on the image links as there are no markings on the chips.

**Comment by xbmcnut** [comment]
Is there a datasheet on the 16-pin radio chip on the remote PCB so I can identify the SPI pins?

**Comment by sidoh** [comment]
I believe this is the PL1167 --

![image](https://user-images.githubusercontent.com/589893/60554533-d6b65800-9cec-11e9-962a-b4c3b9a01619.png)

here's a datasheet:

[2014.2.8_9.21.48_1259.pdf](https://github.com/sidoh/esp8266_milight_hub/files/3352738/2014.2.8_9.21.48_1259.pdf)

this is the pinout:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/589893/60554609-111ff500-9ced-11e9-99a6-1cf5f41fc3d2.png">

relevant pins are:

DVSS - pin 6 - Gnd
SCK - pin 7 - SPI clock
SDO - pin 10 - SPI out
SDI - pin 9 - SPI in

**Comment by xbmcnut** [comment]
That's helpful thanks. And by poking around, I believe I need this program? https://www.saleae.com/downloads/

**Comment by sidoh** [comment]
thats right!

**Comment by cometfish** [comment]
Just wanted to chime in and say I've been following this one, because two of my remotes (one W, one RGB) never came up when sniffing. With the 1.10.0-dev5 build, they're now working! Thankyou! :)

**Comment by xbmcnut** [comment]
Thanks @cometfish I raced home to try dev5 with my two rogues but alas, still no go. Never fear, USB debugger turned up yesterday so Houston, standby...

**Comment by cometfish** [comment]
Sorry @xbmcnut, I should've specified I had skipped straight from the 1.9 release to 1.10.0-dev5 - it was probably the fix in dev4 that helped for my remote.
Good luck with the USB debugger!

**Comment by xbmcnut** [comment]
Started looking at the debugging today but both the working MiLight remote and one of the rogue remotes don't follow the pinout for the PL1167. If you take the dot as indicating pin one, then my antenna is connected to 09 and VCC is on 12 with GND at 14. This does not marry with a PL1167?

![ScreenGrab294](https://user-images.githubusercontent.com/1492137/60764969-2333d600-a0e7-11e9-97b0-e7fa093205e5.jpg)

Any other possibilities for the 2.4G transceiver in a GOP16 configuration?

**Comment by sidoh** [comment]
That looks right to me.  The datasheet I linked is the only PL1167 documentation I'm familiar with.  Could try to find where the trace going to the copper antenna is going as a reference.

The orientation you've described is the one I used as well, I think.  But on vacation now, so can't check :)

**Comment by xbmcnut** [comment]
Schematic for PL1167 shows antenna on 16, VCC on 11 and GND (DVSS) on 6.

**Comment by sidoh** [comment]
The dot on my devices seems to not indicate pin 1.  I had to try some of the other pins towards the end until I found the right ones. :X

**Comment by xbmcnut** [comment]
If you follow my pix above disregarding the pin 1 locater, the antenna, power and GND do not map to the PL1167 no matter which way you try and look at it.

**Comment by sidoh** [comment]
Huh, wacky.  I've tapped the PL1167 pins on I believe 5 different devices, and they're always in the same place.  :-\

**Comment by localhost61** [comment]
Hi @sidoh and @xbmcnut.
I discover this project and it's exactly what I was looking for in order to control two ceiling lights with OpenHab, one is a [48W CCT](https://fr.aliexpress.com/item/-/32996881219.html)+[Leds](https://fr.aliexpress.com/item/32332928591.html), the other a [36W RGB-CCT](https://www.aliexpress.com/item/-/32921763963.html). And I'm already familiar with all the parts of it. But unfortunately it doesn't work as I would expect...
- I cloned at first the master branch but having issues in PlatformIO for windows, telling that several forks of the required version of library were available for nRF24, mqtt and some others I don't recall, back to the blog I ended up to compile latest 10.0-wip and uploaded it on a Wemos D1 mini and a nodeMCU too.
- I connected those ESP to several nRF24L01 I own where one of them is a PA+LNA model.
- No problem to reach the webpage with a browser, I could sniff the packets of the RGB-CCT remote but couldn't manage to control the lamp. And about the CCT one, as it seems I've got a new version of the @xbmcnut 's one with fluorescent buttons, I got nothing at all too.
- I tried to uncommented -D DEBUG_PRINT in platformio.ini and monitor on USB to get more troubleshooting data... and the packets appear in the PIO monitor and no more at the end of the webpage.
- On D1 mini, using esptool,  I uploaded several older pre-compiled Release files too ([RC1](https://github.com/sidoh/esp8266_milight_hub/releases/download/1.10.0-rc.1/esp8266_milight_hub_d1_mini-1.10.0-rc.1.bin), dev8, 1.9.2, [1.6.0-dev3](https://github.com/sidoh/esp8266_milight_hub/releases/download/1.6.0-dev3/esp8266_milight_hub_d1_mini-1.6.0-dev3.bin) with complementary data but no result.

None of my two remotes were referenced as milight products, I believe they are clones of FUT096 and FUT007, all the boards have a 'GM' reference on the silk screen. The interesting, and somewhat scarring, news is that both remote's chips are monolithic. The 2.4GHz RF and the CPU are integrated in a single 16 pin SOIC, and it's not a nRF24 as it doesn't seem to exist in such package. At first sight my RGB-CCT remote shows 2 chips, but U17 appears to be only used  to encode the touch buttons, both Oscillator and Antenna or connected to IC2.
Thus no SPI pins may be available here for diagnose. But... on the 36W controller side, we have two separate chips one 16 pin and one 20 pin, a 80C51 CPU, the [Nuvoton N76E003AT20](http://www.nuvoton.com/resource-files/DS_N76E003_EN_Rev1.07.pdf) with SPI on pins 7,15,16,17.
So I'll have to check if this 16pin chip pinout matches the one on my FUT007 clone and the older one.

Here are the pictures ov my remotes:

![IMAG2565](https://user-images.githubusercontent.com/33861984/62506916-bf461f80-b802-11e9-85bc-251ce1bd03ff.jpg)
 
![IMAG2568](https://user-images.githubusercontent.com/33861984/62506942-d84ed080-b802-11e9-9f7f-de0c91a0ff66.jpg)

![IMAG1655 - Remote PCB](https://user-images.githubusercontent.com/33861984/62506982-fa485300-b802-11e9-8ef2-ffd713722545.jpg)

![IMAG1658 - 2 4GHz PCB](https://user-images.githubusercontent.com/33861984/62507001-0c29f600-b803-11e9-9862-79120301ca67.jpg)

---

![IMAG2191](https://user-images.githubusercontent.com/33861984/62507248-f7019700-b803-11e9-89f0-4d5c667c9ffa.jpg)

![IMAG2560](https://user-images.githubusercontent.com/33861984/62507266-08e33a00-b804-11e9-8827-9b4e2077b83f.jpg)

![IMAG2564](https://user-images.githubusercontent.com/33861984/62507306-316b3400-b804-11e9-8e21-1fa6898ab404.jpg)

**Comment by xbmcnut** [comment]
@localhost61 Thanks so much for your feedback and input. Can you confirm you have the 3.3V, GND and antenna connection on your 16-pin chip like mine (even though I may have the numbering wrong) that in no way match the PL1167? The PL1167 pinout shows the Xtal and Antenna pins on the same side but mine are opposite.

**Comment by localhost61** [comment]
Today, I checked both drivers pinout and results are deceiving.

**RGBCW**
![IMAG2597](https://user-images.githubusercontent.com/33861984/62575865-f4eb1700-b89b-11e9-8769-57bd0f28a8aa.jpg)
- Chips are SSOP with 3.3V power supply. The transceiver marking is erased. Do you know any RF24 transceiver in _SSOP16_ package?
- Pin 6 & 7: 12MHz crystal
- Pin 10: Antenna
- pin 9 & 15: Gnd  ("G" test point)
- pin 12: VDD ("V" test point)
- pin 1 = IC1.3
- pin 2 = IC1.2
- pin 4 = IC1.1
- pin 13 = IC1.20
- pin 14 = IC1.19
- pin 16 = IC1.15
- pin 3, 5, 8 & 11 are tight together

About IC1, the N76E003AT20, its DataSheet says that SPI bus is located on pins 10,15,16,17 but I could see it's not used here as pin 10 is the Red output, and 17 the Green one.
- additionally pin 14 is Blue output, "R" Test point (for Receive?) is pin 4, "S" Test point (for Send?) is pin 18, with multimeter frequency is about 1kHz. Due to dangerous voltage present (LED strip output voltage  is measured at 180V) I'm reluctant to plugin my [Logical Analyzer](https://fr.aliexpress.com/item/32921215066.html) here .
![IMAG2617](https://user-images.githubusercontent.com/33861984/62575975-311e7780-b89c-11e9-8255-ff13331e9a77.jpg)
- On the main driver board, signals for CW and WW travel through a supplementary stage, a JL2233A (?) and it's the same on the RGBCW driver.

**CCT**
![IMAG2598](https://user-images.githubusercontent.com/33861984/62582109-962d9980-b8ab-11e9-9d95-702aaff01c4d.jpg)
![IMAG2600](https://user-images.githubusercontent.com/33861984/62582206-e99fe780-b8ab-11e9-880a-75610873285f.jpg)
On the CCT driver, things are worse, chips are SOP like on the Remote but that's all, the second SOP8 chip is an I²C E²prom 24C02.
- SDA on pin 7, SCL on pin 8 of the RF24 transceiver
- Crystal is between pins 15 & 16
- Antenna on pin 2
- Gnd on pins 1 & 3
- VDD on pins 7 & 14

On my Remote (FUT007 clone see in previous post), it appears that :
- Crystal is between pins 14 & 15
- Antenna on pin 1
- Gnd on pin 16
- VDD on pins 2, 6 & 13
- /LED on pin 9
- I guess that the 8 remaining pins are used for the row and column of the 4x4 matrix of buttons.
=> Nothing to monitor with a Logic Analyzer and different chips are used for Transmit and Receive.

Maybe a RTL-SDR could be the monitoring option. I've received [this one](https://fr.aliexpress.com/item/33030482359.html) some weeks ago, it's bandwidth is large enough and I have the pigtails required to adapt on WiFi antennas. I may learn how to sniff data sent on the air.

**Comment by localhost61** [comment]
It seems I need a [MMDS down converter](https://fr.aliexpress.com/item/32910376325.html) to be able to sniff the air with my RTL-SDR. Order made.
See you in two weeks ;-)

**Comment by xbmcnut** [comment]
I thought you wanted to keep this open Chris?

**Comment by sidoh** [comment]
The official milight RGB remote now works.  

It seems like you may have a different, probably non-milight device, which I don't think I can commit to supporting.  Happy to revisit if you think that assessment is wrong, though.

**Comment by rryk** [comment]
@localhost61 I wonder if you have managed to sniff the data sent by the CCT remote you've described in the Aug 6-8 comments? I have the same remote (PINs and layout all match your description), so would love to either add support for it into this library or fork it.

**Comment by localhost61** [comment]
@rryk  Sorry, I didn't put enough resources in it. Anyway, the driver is dead now. I just ordered it's [successor](https://fr.aliexpress.com/item/1005001658655088.html). It will be WiFi.

**Comment by localhost61** [comment]
The problem with milight products it that they drive only constant voltage 12V/24V lights. My ceiling light uses 230mA constant current and at 48W the resulting voltage is above 100VDC. My other ceiling light is 36W RGB+CCT and if the driver die too, I'm not sure I'll be able to replace it.

**Comment by rryk** [comment]
Thank you for the quick answer. I have bought a lamp with this remote and would be happy to play with the NodeMCU / remote, which only work with low-voltage. However, I do not feel comfortable tinkering with high-voltage on the lamp itself, so I'll probably either ask an electrician to do it or just get myself some drivers to push physical buttons on the actual remote :-).

**Comment by magicmicros** [comment]
I'm late to the party, but want to chime in with some info on the PL1167.
The datasheet posted here earlier (version 0.4, 2012), is NOT correct.
I have attached the correct datasheet (version 0.9, 2012).
I have also attached the User Manual for the PL1167.
As both are from the same supplier, just different versions, it's quite remarkable that the pinout is different.
Anyway, I have, over the last 5-6 years or so, made several designs based on the "real" pinout as well as replaced PL1167's on bulb boards and remotes. And checked the pinning towards that datasheet. 
It works.

To make matters worse, there is (at least) one more pinout version, I saw on AliExpress once. I wanted to link to it, but was not able to find it again.
I've bought PL1167's from multiple suppliers there (Hong Kong CCD Limited, Keteling, e.t.c.)
All have been correct and working.

Hope this clears some things up and helps some.

[PL1167_DS_EN_V0.9.pdf](https://github.com/sidoh/esp8266_milight_hub/files/5938641/PL1167_DS_EN_V0.9.pdf)
[PL1167_UM_EN_V0.2.pdf](https://github.com/sidoh/esp8266_milight_hub/files/5938642/PL1167_UM_EN_V0.2.pdf)

**Comment by synio-wesley** [comment]
@localhost61 I also have a SOP16 SOC 2.4 GHz transceiver in my remote for a ceilig light I purchased a few weeks ago. The remote is pictured here:

![IMG_20220201_222056402](https://user-images.githubusercontent.com/30413/152053477-21968486-51d9-4ebd-9644-448749c89cba.jpg)

The SOC looks very similar to the one in your blue circuit board remote.

While looking online, I found this datasheet: http://www.ledentech.com/uploadfile/HS6206_DataSheet_V0.6_20150302.pdf The HS6206 SOP16 version looks exactly like the one we have (see page 14 for a drawing). It has an embedded microcontroller, so that's probably why it's just one chip.

The datasheet I linked to is very detailed... it might help...?
